{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.liuweile.maven",
    "module": "ads-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ads-sdk-1.0.1.aar",
          "url": "ads-sdk-1.0.1.aar",
          "size": 477967,
          "sha512": "d717e46ac31bf570a43fc294c761574a7b873716ea6b3dd1ab326304a653af40b359e869689d1411666c25e815662d0c2b9cfe6b75f66e9cae8f9cc4cc3b35e6",
          "sha256": "2d8cb1a25fda5f58ce81cdb9da75252d5c796d3879d0b13ebf969ee4407ec46b",
          "sha1": "1b6d41c8eb687397bc1f7581c0a2c46c6a2cb800",
          "md5": "f6730d12b0e44cfa4f531a9725090a65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ads-sdk-1.0.1.aar",
          "url": "ads-sdk-1.0.1.aar",
          "size": 477967,
          "sha512": "d717e46ac31bf570a43fc294c761574a7b873716ea6b3dd1ab326304a653af40b359e869689d1411666c25e815662d0c2b9cfe6b75f66e9cae8f9cc4cc3b35e6",
          "sha256": "2d8cb1a25fda5f58ce81cdb9da75252d5c796d3879d0b13ebf969ee4407ec46b",
          "sha1": "1b6d41c8eb687397bc1f7581c0a2c46c6a2cb800",
          "md5": "f6730d12b0e44cfa4f531a9725090a65"
        }
      ]
    }
  ]
}
